--- #YAML:1.0
name:               Test-PerlTidy
version:            20110323
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Finder:   0
    File::Slurp:    0
    File::Spec:     0
    parent:         0
    Perl::Tidy:     20031021
    Test::Builder:  0
    Test::More:     0
    Text::Diff:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
