---
name: Test-PerlTidy
version: 20050726
author:
  - evdb@ecclestoad.co.uk Edmund von der Burg
abstract: check that all your files are tidy.
license: perl
requires:
  File::Slurp: 0
  Module::Build: 0
  Perl::Tidy: >=20031021
  Test::Builder: 0
  Text::Diff: 0
provides:
  Test::PerlTidy:
    file: lib/Test/PerlTidy.pm
    version: 20050726
generated_by: Module::Build version 0.25
